apiVersion: v1
kind: Service
metadata:
  name: ms-shipping-svc
  labels:
     app: ms-shipping
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
    protocol: TCP
  selector:
     app: ms-shipping
